---
deployment:
  tasks:
    - export PATH=$HOME/node_modules/.bin:$PATH
    - npm install
    - npm run build -- --configuration production
    - rm -rf ~/public_html/*
    - cp -r dist/tera-tech-solutions/* ~/public_html/
